### ISSUE TITLE
Component for :/qml/ReactActivityIndicator.qml is not ready

### ISSUE THREAD

**Issue by loopingrage** [status-im/react-native-desktop#119]
Hey there. I'm interested in using this project for a project I'm working on @ Cisco. We are investing heavily in React Native and have a need to target QT-based devices. I spoke to @vkjr last week and am very grateful that you all have taken the lead on porting React Native to QT.

I have followed the instructions in `Development-linux.md` and they got me pretty far (thanks!). I have QT Creator installed and have successfully built the project. However, when attempting to run the `TicTacToe` example am getting an error that QT is not ready. When inspecting the build directory I can confirm that the referenced QML files are not there. Here is my build log and run log. Any help would be greatly appreciated.

https://gist.github.com/loopingrage/ef1a3f0dba8d6d99ace1a96ebd67437f

**Comment by MaxRis** [comment]
Hello @loopingrage ,

> When inspecting the build directory I can confirm that the referenced QML files are not there
QML files are embedded resources. So it's fine that you can't find them.

> From log file:  SourceCode::loadSource(QNetworkAccessManager*)::<lambda()> : Error while loading source "Connection refused"
It seems that you haven't started react-native's JS packager as separate process in separate terminal tab. To start it, open new terminal tab, navigate to root directory of your react-native-qt clone, run `npm install` to install node modules dependencies (you should have node and npm installed on your machine), and run `npm start` to start packager. You will see output in console that packager is starting and listening port on localhost.

Now you can try to run example again. You should be able to see in packager tab some new output, that running example requested packager to package JS bundle for it.

Hope above helps.
Also please take into account that for development is used process started by running `node ubuntu_server.js`. Via ubuntu_server.js Qt application communicates with Node process which executing JS code received as bundle initially from react-native packager.
You can run `node ubuntu_server.js` in separate terminal tab also. Or it's started automatically from example .sh run script.

**Comment by loopingrage** [comment]
Hello. Thanks for the tips. So I ran the `ubuntu-server` and the `packager` in separate terminal windows and re-ran the project in QT Creator. This time I see an error in the ubuntu-server log: https://gist.github.com/loopingrage/d25b79b020927b23e1cd27a7610166ce

Thanks in advance for all the help.

**Comment by loopingrage** [comment]
I should mention that the run log in QT Creator looks the same:

```

Starting /home/jodecast/projects/react-native-linux-build/Examples/TicTacToe/run-example.sh...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Object.<anonymous> (/home/jodecast/projects/react-native-linux/ubuntu-server.js:118:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
"Component for :/qml/ReactActivityIndicator.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactActivityIndicator.qml: File not found)
"RCTActivityIndicatorView" has no view for inspecting!
"Component for :/qml/ReactButton.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactButton.qml: File not found)
"RCTButtonView" has no view for inspecting!
"Component for :/qml/ReactImage.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactImage.qml: File not found)
"RCTImageView" has no view for inspecting!
"Component for :/qml/ReactModal.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactModal.qml: File not found)
"RCTModalHostView" has no view for inspecting!
"Component for :/qml/ReactNavigator.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactNavigator.qml: File not found)
"RCTNavigator" has no view for inspecting!
"Component for :/qml/ReactRawText.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactRawText.qml: File not found)
"RCTRawText" has no view for inspecting!
"Component for :/qml/ReactScrollView.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactScrollView.qml: File not found)
"RCTScrollView" has no view for inspecting!
"Component for :/qml/ReactSlider.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactSlider.qml: File not found)
"RCTSlider" has no view for inspecting!
"Component for :/qml/ReactText.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactText.qml: File not found)
"RCTText" has no view for inspecting!
"Component for :/qml/ReactTextInput.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactTextInput.qml: File not found)
"RCTTextInputView" has no view for inspecting!
"Component for :/qml/ReactView.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactView.qml: File not found)
"RCTView" has no view for inspecting!
QQmlComponent: Component is not ready
void RedboxItemPrivate::createRedboxItem(QQuickItem*) Unable to create RedboxItem (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactRedboxItem.qml: File not found)
/home/jodecast/projects/react-native-linux-build/Examples/TicTacToe/run-example.sh: line 4: 29119 Segmentation fault      (core dumped) qmlscene -I /home/jodecast/projects/react-native-linux-build/ReactQt/runtime/src/ /home/jodecast/projects/react-native-linux-build/Examples/TicTacToe/TicTacToe.qml
/home/jodecast/projects/react-native-linux-build/Examples/TicTacToe/run-example.sh exited with code 139
```

**Comment by MaxRis** [comment]
Hi @loopingrage ,

> Error: listen EADDRINUSE :::5000  
Above error is fine, means that port is occupied already by some another node process started previously with `node ubuntu_server.js`
It doesn't matter if you have it already running or start new one.
You can check the app occupying specific port by running
`lsof -i :5000`

> "Component for :/qml/ReactTextInput.qml is not ready!" (file:///home/jodecast/projects/react-native-linux-build/:/qml/ReactTextInput.qml: File not found)
Errors like this, seems, mean that Qt app can't find files embedded as resources. Since, according to your packager's log, it returned JS bundle successfully, this looks for me like something is broken.

In latest PR we might will change logic to load resources from `qrc:` URL ( https://github.com/status-im/react-native-linux/pull/124/files#diff-22afd47f09aabb3011c1d5fa389dd8c8R81 )

Are you trying to run example on latest react-native-qt branch commits?
I will try to repro the failure locally.

**Comment by MaxRis** [comment]
Pretty strange, but TicTacToe example started from Qt Creator with executable path `./Examples/TicTacToe/run-example.sh` starting and works fine on my local machine.

**Comment by loopingrage** [comment]
Yes, I'm on the latest from `react-native-qt`. I'll blow away what I have and start over. Thanks.

**Comment by MaxRis** [comment]
@loopingrage , I'm supposing to merge today PR with changes to use `qrc:` URLs instead of file path schemas. This might also resolve or change output of the failure. I will update you here.

**Comment by MaxRis** [comment]
also if you will provide TeamViewer credentials for remote access of your build machine to my email risuhin.max@gmail.com I will able to find some time to connect and check myself directly on your machine.

**Comment by MaxRis** [comment]
@loopingrage https://github.com/status-im/react-native-linux/pull/124 is merged
Could you please try to pull `react-native-qt` branch and do rebuild.
P.S. You will need to do "npm install" on root of your clone, since new JS dependency modules were added

**Comment by loopingrage** [comment]
Wow. Much better. I pulled the latest and the TicTacToe example is working now.

I did observe that the Xs and Os are misaligned though (see attached screenshot). Also, the log still contained a few errors.

```
Starting /home/jodecast/projects/react-native-linux-build/Examples/TicTacToe/run-example.sh...
-- Server starting
"Component for qrc:/qml/ReactActivityIndicator.qml is not ready!" (qrc:/qml/ReactActivityIndicator.qml:1:1: module "QtQuick" version 2.9 is not installed)
"RCTActivityIndicatorView" has no view for inspecting!
"Component for qrc:/qml/ReactButton.qml is not ready!" (qrc:/qml/ReactButton.qml:1:1: module "QtQuick" version 2.9 is not installed)
"RCTButtonView" has no view for inspecting!
"Component for qrc:/qml/ReactImage.qml is not ready!" (qrc:/qml/ReactImage.qml:1:1: module "QtQuick" version 2.7 is not installed)
"RCTImageView" has no view for inspecting!
"Component for qrc:/qml/ReactModal.qml is not ready!" (qrc:/qml/ReactModal.qml:1:1: module "QtQuick" version 2.9 is not installed)
"RCTModalHostView" has no view for inspecting!
"Component for qrc:/qml/ReactSlider.qml is not ready!" (qrc:/qml/ReactSlider.qml:1:1: module "QtQuick" version 2.9 is not installed)
"RCTSlider" has no view for inspecting!
"Component for qrc:/qml/ReactTextInput.qml is not ready!" (qrc:/qml/ReactTextInput.qml:1:1: module "QtQuick" version 2.7 is not installed)
"RCTTextInputView" has no view for inspecting!
-- Connection from RN client
Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
Warning: Invalid argument supplied to oneOf, expected an instance of array.
Warning: Invalid argument supplied to oneOf, expected an instance of array.
Warning: Invalid argument supplied to oneOf, expected an instance of array.
Running application "TicTacToeApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Send event:  "touchStart"
Send event:  "touchEnd"
Send event:  "touchStart"
Send event:  "touchEnd"
Send event:  "touchStart"
Send event:  "touchStart"
Send event:  "touchEnd"
Send event:  "touchStart"
Send event:  "touchEnd"
Send event:  "touchStart"
Send event:  "touchStart"
Send event:  "touchEnd"
Send event:  "touchStart"
Send event:  "touchStart"
Send event:  "touchEnd"
"No such interface 'org.freedesktop.DBus.Properties' on object at path /"
"No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/0"
"No such interface 'org.freedesktop.DBus.Properties' on object at path /"
```

Screenshot
![screenshot from 2017-10-16 08-55-48](https://user-images.githubusercontent.com/52177/31622063-354d32d2-b250-11e7-9232-3dceddfcbb84.png)

**Comment by vkjr** [comment]
@loopingrage, `module "QtQuick" version 2.9 is not installed` means that you don't have Qt libraries installed systemwide.
These commands used to setup Qt environment in our `Circle CI` config:
'''
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
          sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
          sudo apt-get -qy update
          sudo apt-get install -y dbus xvfb curl cmake mesa-common-dev \
              qt59base qt59graphicaleffects qt59quickcontrols2 qt59declarative
'''

**Comment by MaxRis** [comment]
@loopingrage great!
> I did observe that the Xs and Os are misaligned though 
That's known issue of Yoga layout related changes, hopefully, we already should have ticket for it.

**Comment by vkjr** [comment]
@MaxRis, yes, we have - #94

**Comment by loopingrage** [comment]
Thanks for being so responsive! I added the new repos but can't seem install the remaining packages:

```
jodecast@ubuntu-native:~/projects/react-native-linux-build/Examples/Text$ sudo apt-get -qy update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Ign:3 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Hit:6 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial InRelease
Ign:7 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial Release
Ign:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Err:8 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:9 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main i386 Packages
Ign:10 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 306 kB in 15s (19.8 kB/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt591-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
jodecast@ubuntu-native:~/projects/react-native-linux-build/Examples/Text$ 
jodecast@ubuntu-native:~/projects/react-native-linux-build/Examples/Text$ 
jodecast@ubuntu-native:~/projects/react-native-linux-build/Examples/Text$ 
jodecast@ubuntu-native:~/projects/react-native-linux-build/Examples/Text$ sudo apt-get install -y dbus xvfb curl cmake mesa-common-dev qt59base qt59graphicaleffects qt59quickcontrols2 qt59declarative
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt59base
E: Unable to locate package qt59graphicaleffects
E: Unable to locate package qt59quickcontrols2
E: Unable to locate package qt59declarative
```

**Comment by vkjr** [comment]
Closing this one. Please open new issue if you still experience problems with project.
Thanks.
