### ISSUE TITLE
Documentation on running RNTester, Examples, and fresh projects

### ISSUE THREAD

**Issue by madhavarshney** [status-im/react-native-desktop#245]
Hi there, I was trying to bootstrap a project with react-native-desktop on MacOS and couldn't get the code to run.  I noticed that some parts of the documentation for adding desktop support to a project are missing, such needing to install cmake, and that some parts of the scripts are not written for MacOS (as shown in the output below: hostname -I and gnome-terminal).  Would you mind telling me how to get the code to run?  (By the way, I installed Qt 5.9.5 instead of 5.9.1, but technically that shouldn't matter since 5.9.5 is just a patch release upgrade.)

```
Starting the app...
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
./run-app.sh: line 72: 31826 Abort trap: 6           ...../RNDesktopTest/desktop/bin/RNDesktopTest $args
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn gnome-terminal ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I also tried to build react-native-desktop somewhat following the docs at https://github.com/status-im/react-native-desktop/blob/master/README-ubuntu.md#developing-react-native-desktop and run one of the examples, but that failed with `file:///react-native-desktop/build/Examples/TicTacToe/TicTacToe.qml:3 module "React" is not installed`.  PR #244 also doesn't seem to add the necessary steps.

### Steps to Reproduce

1.  Start on a fresh Mac without the react-native-desktop environment setup
2.  Follow the documentation to install the custom react-native cli and create a new project:
3.  https://github.com/status-im/react-native-desktop/blob/master/docs/ReactQt/InstallUpdatedReactNativeCLI.md
4.  https://github.com/status-im/react-native-desktop/blob/master/docs/ReactQt/InstallPrerequisites.md
5.  https://github.com/status-im/react-native-desktop/blob/master/docs/ReactQt/CreateNewApp.md
6.  Start the app using react-native run-desktop, which fails

### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.2.0 => 16.4.0
  react-native: https://github.com/status-im/react-native-desktop#master => 0.53.3

Target Platform: MacOS

Thanks, Madhav.

**Comment by vkjr** [comment]
Hi @madhavarshney, thank you for trying the project.
Do you have qmake available in the PATH? If not, you need to execute following:
`export PATH=<QT_PATH>/clang_64/bin:$PATH`

**Comment by MaxRis** [comment]
Hey @madhavarshney ,

> couldn't get the code to run. I noticed that some parts of the scripts are not written for MacOS

Please note that doc https://github.com/status-im/react-native-desktop/blob/master/docs/ReactQt/CreateNewApp.md is updated recently with few additional steps for MacOS. (because of missed steps in script as you mentioned)

The terminal where you are trying to run `react-native run-desktop` should be with correct `qmake` and `cmake` tools available in the PATH.

Thanks,
Max

**Comment by madhavarshney** [comment]
Thanks @vkjr and @MaxRis.  I actually have done all of the those, as qmake, cmake, and other Qt tools are in my path.  I also launched both the metro bundler and ubuntu-server.js before running `react-native run-desktop`, but that didn't help.  I think this has to do with either my Qt setup or the desktop code generated.  The same error also comes after I build react-native-desktop (with Qt Creator) and try to run it.

**Comment by madhavarshney** [comment]
That issue turned out to be with my Qt setup.  After I added the environment variables listed [here](https://github.com/pyqt/python-qt5/wiki/Qt-Environment-Variable-Reference), the code was able to run and the app opened, but metro bundler failed to bundle the code with the following error:
```
error: bundling failed: ambiguous resolution: module `...../RNDesktopTest/node_modules/react-native/Libraries/react-native/react-native-implementation.js` tries to require `Button`, but there are several files providing this module. You can delete or fix them:

  * `...../RNDesktopTest/node_modules/react-native/Libraries/Components/Button.desktop.js`
  * `...../RNDesktopTest/node_modules/react-native/Libraries/Components/Button.js`
``` 
Do I have to add a custom `rn-cli.config.js` and blacklist modules to fix this issue?

**Comment by vkjr** [comment]
`react-native-desktop` patches bundler code to add 'desktop' platform.
That happens when you run `react-native desktop` command.

If you were reinstalling node modules after `react-native desktop` invocation, it could be that you have bundler again unpatched and *.desktop.js files unrecognized.

Please, take a look at `node_modules/metro/src/defaults.js` file, it should contain string:
`exports.platforms = ['ios', 'android', 'windows', 'web', 'desktop']`

If it lacks `desktop` mention, you need to apply patch again by calling `react-native desktop` command one more time

**Comment by madhavarshney** [comment]
The other option that you may want to document is adding getPlatforms to your `rn-cli.config.js` as such:

```js
module.exports = {
    getPlatforms: () => ['ios', 'android', 'desktop'], // And other target platforms like 'web'
}
```

**Comment by madhavarshney** [comment]
Yes the app is up and running now, thanks for your help!  Would you mind if I send PR to improve the documentation after my experience with react-native-desktop?

> Can this patch be merged with metro?

The reason I said this was because there are already other "extra" platforms in the defaults, such as 'web' and 'windows'.

**Comment by vkjr** [comment]
>Yes the app is up and running now, thanks for your help! Would you mind if I send PR to improve the documentation after my experience with react-native-desktop?

Yes, you are welcome!

>The reason I said this was because there are already other "extra" platforms in the defaults, such as 'web' and 'windows'.

Creating the issue in `metro` repository right now :)

**Comment by vkjr** [comment]
@madhavarshney, did I understand correctly that you added abovementioned `rn-cli.config.js` to your project directory and could run the app without patching `metro/src/defaults.js`?

Do you specify config when running `react-native run-desktop`?

**Comment by vkjr** [comment]
Thanks!
@MaxRis, it can be a good alternative to patching metro.

**Comment by madhavarshney** [comment]
@vkjr - I tried to build and run the app on windows but `react-native run-desktop` fails with this error:

```
Scanning folders for symlinks in D:\Madhav\projects\adapt\RNDesktopTest\node_modules (44ms)
Found desktop external modules: undefined
Found desktop JS bundle path: undefined
Building the app...

Command failed: build.bat -g "MinGW Makefiles"
CMake Error at D:/...../RNDesktopTest/node_modules/react-native/ReactQt/runtime/src/CMakeLists.txt:26 (find_package):
  By not providing "FindQt5WebKit.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5WebKit", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKit" with
  any of the following names:

    Qt5WebKitConfig.cmake
    qt5webkit-config.cmake

  Add the installation prefix of "Qt5WebKit" to CMAKE_PREFIX_PATH or set
  "Qt5WebKit_DIR" to a directory containing one of the above files.  If
  "Qt5WebKit" provides a separate development package or SDK, be sure it has
  been installed.
```

If I remove `if (WIN32) set(USE_QTWEBKIT 1) endif()` from `RNDesktopTest/desktop/CMakeLists.txt`, then the code builds without any errors.  Apparently QtWebKit was not installed with the packages listed in the documentation, so is it supposed to be added separately?.

**Comment by madhavarshney** [comment]
As a sidenote, that block of code seems to have been removed in [status-react/desktop/CMakeLists.txt](https://github.com/status-im/status-react/blob/desktop/desktop/CMakeLists.txt).

**Comment by vkjr** [comment]
That block of code is correct and should be also inserted in CMakeLists.txt you pointed to :)

On Windows we use QtWebKit to implement <WebView> control. As you mentioned, it is probably not installed on your machine. Not sure if it is enabled by default in Qt installation.
You can run `maintananceTool` from Qt, select `add/remove components` and add QtWebKit to your installation

**Comment by vkjr** [comment]
Right now WebEngine can't be built with MinGW. And `react-native-desktop` doesn't support yet build with msvc. So we use QtWebKit for now.
@MaxRis, could you please help, how QtWebKit should be installed?

**Comment by madhavarshney** [comment]
Seems like QtWebKit needs to be built from source... I guess I don't need WebView for now.  What exactly needs to be done to support an MSVC build on windows?

**Comment by MaxRis** [comment]
@madhavarshney you should be able safely remove `if (WIN32) set(USE_QTWEBKIT 1) endif()` till the moment you will need to use react-native's WebView component in your app.

> Seems like QtWebKit needs to be built from source
Yes, it should be built from sources or, probably, you can get some pre-built ( I have built one for Qt 5.9.1 against official Qt 5.9.1 Qt MinGW distribution but it's not shared with public access at the moment )

> What exactly needs to be done to support an MSVC build on windows?
To support static build of react-native library with MSVC it seems it's required to cleanup source code from unix only definitions and constraints (hopefully, not too much work). But building of react-native library as shared dll is not supported for both MinGW and MSVC. Since on Windows all shared lib methods are not exported by default, it's required to mark them explicitly to be exported from dll. This functionality is not available at the moment. + MSVC has specific requirements to put exported methods into the import lib.
As you might found already, building of QtWebKit is not required for MSVC toolchain, since Qt MSVC build goes with QWebEngine based on Chromium.

**Comment by MaxRis** [comment]
> @MaxRis, it can be a good alternative to patching metro.

@vkjr this should be great to implement. But additionally we're patching metro bundler to allow to allocate more memory for JS heap on node Workers processes (which are gathering js bundle into single file)

**Comment by madhavarshney** [comment]
@MaxRis - If that patch can also be merged with metro, then it will be much easier to use react-native-desktop with a variety of package managers / configurations.  However, (so far) I haven't seen any difference without that portion of the patch applied.

I tried building react-native-desktop with Qt Creator based on the Linux development guide and then running the `ReactNativeApp` target with the build set to `Debug` but metro (`node .\local-cli\cli.js start`) fails with the following error after the application launches on both MacOS and Windows: 

```
error: bundling failed: NotFoundError: Cannot find entry file index.desktop.js in any of the roots: ["D:\\.....\\react-native-desktop"]
    at DependencyGraph.getAbsolutePath (D:\.....\react-native-desktop\node_modules\metro\src\node-haste\DependencyGraph.js:304:11)
    at D:\.....\react-native-desktop\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:265:416
    at Generator.next (<anonymous>)
    at step (D:\.....\react-native-desktop\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:13:629)
    at D:\.....\react-native-desktop\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:13:789
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Is `ReactNativeApp` not meant to be run and only the examples and RNTester are meant to be run?  I tried running RNTester and a bunch of the examples with the following command from my cli:

`qmlscene -I D:\.....\build-react-native-desktop-Desktop_Qt_5_9_5_MinGW_32bit-Debug\ReactQt\runtime\src\ D:\.....\react-native-desktop\RNTester\qml\RNTester.qml`

But all such invocations result in `file:///D:/...../react-native-desktop/RNTester/qml/RNTester.qml:12 module "React" is not installed`.  It seems like the switch `-I D:\.....\ReactQt\runtime\src\` doesn't seem to have any effect.  I also tried adding a custom `Run` configuration with the configuration below but that fails with the same error.

```
Executable: qmlscene
Command line arguments: -I .\build-react-native-desktop-Desktop_Qt_5_9_5_MinGW_32bit-Debug\ReactQt\runtime\src\ .\build-react-native-desktop-Desktop_Qt_5_9_5_MinGW_32bit-Debug\Examples\Button\Button.qml
Working directory: D:\.....\

**Comment by vkjr** [comment]
Here are my settings in `react-native-desktop` projects to run RNTester:

<img width="806" alt="screen shot 2018-06-08 at 12 06 09 pm" src="https://user-images.githubusercontent.com/5786310/41149544-7e155954-6b14-11e8-81a1-0c89140b0408.png">

**Comment by vkjr** [comment]
@madhavarshney, if it is not a secret, what is your use case for `react-native-desktop`? Do you plan to develop desktop `react-native` apps with it? Or maybe you already have an existing one that you want to port?
Thanks.

**Comment by MaxRis** [comment]
Hey @madhavarshney ,

> @MaxRis - If that patch can also be merged with metro, then it will be much easier to use react-native-desktop with a variety of package managers / configurations. However, (so far) I haven't seen any difference without that portion of the patch applied.

Increasing of JS heap size required for too big JS bundles transformation (if JS bundle takes, maybe, more than 2MB). It's a known issue of metro bundler from pretty old times, but I'm not sure why it's not yet fixed. Or maybe I'm not aware about better solution, than patching. To increase JS heap space for child Node.JS processes it's required just to pass special cmd flag on new Node.JS process launching. If in latest metro packager version they have allowed to pass such custom cmd flag from high level, that will be the best solution without any patching...
