### ISSUE TITLE
Duplicate module name renderApplication

### ISSUE THREAD

**Issue by tonn** [status-im/react-native-desktop#357]
## Environment
```
  "dependencies": {
    "react": "16.4.1",
    "react-native": "github:status-im/react-native-desktop"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.6.0",
    "react-test-renderer": "16.4.1"
  },
```
```
C:\Workspaces\_Temp\20181003\reactNativeDesktop>npx react-native info
Scanning folders for symlinks in C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules (36ms)

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 5.88 GB / 15.80 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246
```

## Description
I created new application according to docs/CreateNewApp.md
And I started it by command:
`cmd /C "set PATH=%PATH%;C:/Qt/Tools/mingw530_32/bin && set CMAKE_PREFIX_PATH=C:/Qt/5.9.1/mingw53_32; && npx react-native run-desktop"`

There was few console windows appearance. But there was no application appearance so I ran `desktop/bin/reactNativeDesktop.exe` manually.
I got this: https://i.imgur.com/CEA4fkq.png

```
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\react-native\Libraries\ReactNative\renderApplication
  Paths: C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\react-native\Libraries\ReactNative\renderApplication.js collides with C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\react-native\Libraries\ReactNative\renderApplication.desktop.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\jest-haste-map\build\index.js:446:17)
    at workerReply (C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\jest-haste-map\build\index.js:496:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 BUNDLE  [desktop, dev] ./index.desktop.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

**Comment by vkjr** [comment]
Hi @tonn!
This error happens when metro bundler not aware of `desktop` platform and as a result it can't distinguish files.

Did you run `react-native desktop` before `react-native run-desktop` ?

That command should create `desktop` subfolder in your project and also patch metro to add `desktop` platform to it. 

p.s.
Patching happens here - https://github.com/status-im/react-native-desktop/blob/master/local-cli/desktop/genDesktop.js#L18

**Comment by tonn** [comment]
> Did you run `react-native desktop` before `react-native run-desktop` ?

I tried it again and noticed error with patching:
```
C:\Workspaces\_Temp\20181003\reactNativeDesktop>npx react-native desktop
Scanning folders for symlinks in C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules (42ms)
Std output:
exec error: Error: Command failed: pwd && patch --verbose -d ./node_modules/metro/src/JSTransformer -i ../../../react-native/increase_bundler_memory_usage.patch
'pwd' is not recognized as an internal or external command,
operable program or batch file.

Std output:
exec error: Error: Command failed: pwd && patch --verbose -d ./node_modules/metro/src -i ../../react-native/add-desktop-platform.patch
'pwd' is not recognized as an internal or external command,
operable program or batch file.

identical index.desktop.js
   create desktop\CMakeLists.txt
   create desktop\build.bat
   create desktop\run-app.bat.in
   create desktop\bin\ubuntu-server.js
   create desktop\main.cpp
To run your app on your Desktop natively:
   cd C:\Workspaces\_Temp\20181003\reactNativeDesktop
   react-native run-desktop
```

There is no such executables (pwd and patch) in MinGW. So looks like I need some another dependencies.

**Comment by vkjr** [comment]
Ok, now it is quite obvious :)

To get further without waiting for fix you can edit file `node_modules/metro/src/defaults.js` to have such line:
`exports.platforms = ['ios', 'android', 'windows', 'web', 'desktop'];`
That should solve problem locally.

You can also change the description of this issue due to new findings and assign a `bug` label. 
Thanks!

**Comment by tonn** [comment]
Manual patching was helped. But I got new error:
```
error: bundling failed: Error: Unable to resolve module `AccessibilityInfo` from `C:\Workspaces\_Temp\20181003\reactNativeDesktop\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map
```

**Comment by vkjr** [comment]
Could you please share the code?

**Comment by tonn** [comment]
There is no "my code". Just what was generadet by react-native and react-native desktop.
I compressed whole working folder
https://drive.google.com/file/d/1Vcm1tij16CyQcMRW5dv9vtqJQ7uRG89l/view?usp=sharing

ps: I removed from cmakelist.txt section about qt5webkit

**Comment by MaxRis** [comment]
Hey @tonn ,
It's possible that build is broken by recent merge of react-native 0.56
You can give a try for last commit based on previous supported version of react-native

https://github.com/status-im/react-native-desktop/commit/da6a673bae81cdbb8ac70a3de3d58e5adfa4ac02

Hopefully, you can stick to this commit hash directly in package.json of your project by setting URL as `https://github.com/status-im/react-native-desktop#da6a673bae81cdbb8ac70a3de3d58e5adfa4ac02` and just run `npm install react-native` to re-install on specified version.

**Comment by tonn** [comment]
So. After 
1) Using specific commit `react-native init reactNativeDesktop --version status-im/react-native-desktop#da6a673bae81cdbb8ac70a3de3d58e5adfa4ac02`
2) Removing qt5webkit section from desktop/cmakelist.txt
3) Manually patching `node_modules/metro/src/defaults.js`
Application still not start by command `react-native run-desktop`. I have to run executable from bin by myself.
I got empty application window https://i.imgur.com/QcHiGpn.png
But there is some simple default content in index.desktop.js

**Comment by MaxRis** [comment]
@tonn 

on your screenshot you are starting `node ubuntu_server` to execute all JS code there, but server doesn't receive the connection.
it's because when you start executable directly it doesn't receive config param that JS execution will be done on `node ubuntu_server` and instead it tries to create separate QProcess running `node ubuntu_server`.
Please try locate in your `desktop/main.cpp` following line https://github.com/status-im/react-native-desktop/blob/master/ReactQt/application/src/main.cpp#L119 and change the value to `QString m_executor = "RemoteServerConnection";`
Then you need to rebuild native code and start executable manually again. In `node ubuntu_server` terminal window you should see something like `New incoming connection` and, probably, more useful output will appear there (some JS error or etc).

**Comment by tonn** [comment]
I fixed my run script. I made some cmd.exe related mistakes
```
cmd /C "set PATH=%PATH%;C:/Qt/Tools/mingw530_32/bin;C:/Qt/5.9.1/mingw53_32/bin; && set CMAKE_PREFIX_PATH=C:/Qt/5.9.1/mingw53_32; && npx react-native run-desktop"
```
I started project from scratch again and used new run script. Now application starting by run script properly.
"ubuntu-server" console is still empty. But I had some errors in other:
https://i.imgur.com/whJWn6o.png
https://gist.github.com/tonn/ca1189718f1cff07f19878f9d551605c
