### ISSUE TITLE
Using dotnetify with react-native-desktop

### ISSUE THREAD

**Issue by writzx** [status-im/react-native-desktop#452]
While trying to use dotnetify with react-native-desktop, I keep on getting this exception.
When trying to the same dotnet project with pure react or react-native, it works as expected. I am not sure what is the error in this case since I didn't find any useful information about this error message while googling it.

```
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLKEENLFUL13" bad request data: "Request line too long."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request line too long.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

I would like to know any workarounds for this problem or leads on why this is happening.

**Comment by writzx** [comment]
Turns out the error was due to the ubuntu server requiring the 5000 port. ASP.net server overrides the port when it starts and thats why the error was "Request line too long."

However I am still not able to get it working correctly but I believe thats a completely different issue.

**Comment by vkjr** [comment]
@writzx, unfortunately I never worked with dotnetify so not sure if I can help...

**Comment by writzx** [comment]
Although its a bit off topic, I would like to add to it.

After identifying the previous error and fixing it on the ASP.NET server side, I am facing the problem where the server request made by dotnetify (from js side) wont go through to the ASP.net server. The cause of that is most probably CORS. 

The only hint I have is this line from the ubuntu node server.

```
Running application "PurpleAttache" with appParams: {"initialProps":{},"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Starting call sendRequest on RCTNetworkingNative... method:POST url: http://localhost:7000/dotnetify/negotiate
``` 

However the ASP.NET server does not log any request received.

Generally, in case of CORS errors the ASP.NET server at least logs all the requests received.
